### ISSUE TITLE
Style cleanup and consolidation

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#1705]
Our styles as obviously not in great shape - such is life - lets try and find common components and apply consistent styles to these areas.
- [ ] Dashboard
- [x] Course List (#1791)
- [x] Course details (#1771)
- [x] Learner group list (#1791)
- [x] Learner group details (#2282)
- [x] instructor groups list (#1791)
- [x] instructor group details (#2360)
- [x] School List (#1791)
- [x] School Details (#2377)
- [x] Programs list (#1791)
- [x] Program details (#2575)
- [x] Program Year details (#2583)
- [x] Admin Dashboard (#1806)
- [x] Users List (#2718)
- [x] New user form
- [ ] Cohort Assignment list
- [ ] Pending user updates list
- [ ] Single user
- [ ] Curriculum inventory
- [ ] Session List
- [ ] Publish all sessions
- [ ] Print Course
- [ ] Session Publication check (#3135)
