### ISSUE TITLE
getting Curriculum Inventory tools out of beta

### ISSUE THREAD

**Issue by stopfstedt** [ilios/frontend#2011]
The following issues need to be addressed in order to get this thing out of beta:
- [x] complete translations (refs #2013, #2014)
- [x] provide test coverage (refs #2012)
- [x] update user guide (refs #2015)
- [x] bug #1990 
- [x] bug #1991
- [x] bug #1992 
- [x] bug #1993

**Comment by jrjohnson** [comment]
@stopfstedt can this be closed?

**Comment by stopfstedt** [comment]
done and _done_!
