### ISSUE TITLE
Prepare codebase for Ember 3

### ISSUE THREAD

**Issue by stopfstedt** [ilios/frontend#3289]
start by checking for deprecations. file additional tickets for addressing these individual deprecations as you find them:

https://emberjs.com/deprecations/v2.x/

What follows is a list of deprecations introduced to Ember.js during the 2.x cycle which will be removed with Ember 3.0.0:

## Deprecations added in 2.1

- [x] [INITIALIZER ARITY](https://emberjs.com/deprecations/v2.x/#toc_initializer-arity)
- [ ] [EMBER.APPLICATION#REGISTRY / EMBER.APPLICATIONINSTANCE#REGISTRY](https://emberjs.com/deprecations/v2.x/#toc_ember-application-registry-ember-applicationinstance-registry)
- [ ] [EMBER.APPLICATIONINSTANCE#CONTAINER](https://emberjs.com/deprecations/v2.x/#toc_ember-applicationinstance-container)
- [x] [EMBER DEBUG FUNCTION OPTIONS](https://emberjs.com/deprecations/v2.x/#toc_ember-debug-function-options)
- [x] [EMBER.COMPONENT#DEFAULTLAYOUT](https://emberjs.com/deprecations/v2.x/#toc_ember-component-defaultlayout)

## Deprecations added in 2.3
- [ ] [INJECTED CONTAINER ACCESS](https://emberjs.com/deprecations/v2.x/#toc_injected-container-access)

## Deprecations added in 2.6
- [x] [EMBER.COMPONENT#DIDINITATTRS](https://emberjs.com/deprecations/v2.x/#toc_ember-component-didinitattrs)
- [x] [MODEL PARAM IN {{render HELPER](https://emberjs.com/deprecations/v2.x/#toc_model-param-in-code-render-code-helper)

## Deprecations added in 2.7

- [ ] [EMBER.BINDING](https://emberjs.com/deprecations/v2.x/#toc_ember-binding)

## Deprecations added in 2.8
- [x] [USE EMBER.STRING.HTMLSAFE OVER EMBER.HANDLEBARS.SAFESTRING
](https://emberjs.com/deprecations/v2.x/#toc_use-ember-string-htmlsafe-over-ember-handlebars-safestring)
- [x] [ENUMERABLE#CONTAINS](https://emberjs.com/deprecations/v2.x/#toc_enumerable-contains)

## Deprecations added in 2.11
- [x] [{{render HELPER](https://emberjs.com/deprecations/v2.x/#toc_code-render-code-helper)
- [x] [RENDERING INTO A {{RENDER}} HELPER THAT RESOLVES TO AN {{OUTLET}}.](https://emberjs.com/deprecations/v2.x/#toc_rendering-into-a-render-helper-that-resolves-to-an-outlet)

## Deprecations added in 2.12

- [ ] [Ember.K](https://emberjs.com/deprecations/v2.x/#toc_code-ember-k-code)

then, check for deprecation warning emitted by addons.

**Comment by jrjohnson** [comment]
Also change 'silence' to 'throw' in https://github.com/ilios/frontend/blob/master/config/deprecation-workflow.js and run tests to see what is in need to fixing.
