### ISSUE TITLE
[meta] Re-design offering manager

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#4809]
This is a meta ticket for re-building the offering creation / editing forms and actions. Linking tickets here to be addressed in any re-design.

- [ ] #1149
- [x] #1703
- [x] #1776
- [x] #2162
- [x] #2253
- [x] #2424 
- [x] #2477
- [ ] #3068
- [x] #3142
- [x] #3143
- [ ] #3363
- [x] #3402
- [ ] #3816
- [ ] #3848
- [x] #3986
- [x] #4647
- [x] #4742 
- [x] #5110
- [x] https://github.com/ilios/common/issues/899
- [x] https://github.com/ilios/common/issues/903
- [x] https://github.com/ilios/common/issues/909
- [x] https://github.com/ilios/common/issues/964
- [x] https://github.com/ilios/common/issues/1270
- [x] https://github.com/ilios/common/issues/1684

**Comment by jrjohnson** [comment]
Closing meta tickets.
